### ISSUE TITLE
Error getting token

### ISSUE THREAD

**Issue by markzolotoy** [SyntakSoftware/ApothecaricApi#2]
I am finally able to run it. I am getting following errors:
http://localhost:32557/api/Account/Token:1 POST http://localhost:32557/api/Account/Token 500 (Internal Server Error)

and:
Access to XMLHttpRequest at ‘http://localhost:32557/api/Account/Token’ from origin ‘http://localhost:4200’ has been blocked by CORS policy: No ‘Access-Control-Allow-Origin’ header is present on the requested resource.

Any idea?

Thanks

**Comment by SyntakSoftware** [comment]
Do you have CORS set up and enabled in the API project?

**Comment by markzolotoy** [comment]
I thought your solution/code do it. Is there anything else I need to do outside of the blog?

**Comment by SyntakSoftware** [comment]
This is not an issue.
